# Generated by Django 3.1.6 on 2021-02-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=30, verbose_name='имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=30, verbose_name='фамилия')),
                ('registration_email', models.EmailField(help_text='Введите e-mail', max_length=40, verbose_name='e-mail')),
                ('registration_role', models.CharField(choices=[{'студент', 'one'}, {'two', 'преподоватль'}], help_text='Выберите роль', max_length=10, verbose_name='роль')),
                ('registration_password', models.CharField(help_text='Введите пароль', max_length=40, verbose_name='пароль')),
            ],
        ),
    ]
