# Generated by Django 3.1.6 on 2021-02-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_email',
            field=models.EmailField(help_text='Введите e-mail', max_length=30, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_role',
            field=models.CharField(choices=[('one', 'студент'), ('two', 'преподоватль')], help_text='Выберите роль', max_length=10, verbose_name='роль'),
        ),
    ]
